"use client";

/**
 * IMStrategy — Strategy & Signals page.
 *
 * Displays the CURRENT NIFTY strategy signal generated by HedgingStrategyEngine
 * via GET /api/indian/signal.
 *
 * RULES:
 *  - Zero hardcoded strategy values (strikes, premiums, max-loss, P&L, etc.)
 *  - If signal.status === NO_TRADE → show NO TRADE card with exact backend reasons
 *  - If backend unreachable → show BACKEND DISCONNECTED
 *  - If data is synthetic/stale → show DATA UNAVAILABLE (never show fabricated setup)
 *  - ₹1,000 max-loss gate lives in the backend; this component only displays results
 *  - PAPER_TRADING=true / LIVE_TRADING=false invariants never change here
 */

import React, { useState, useEffect, useCallback } from "react";
import {
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Wifi,
  WifiOff,
  RefreshCw,
  Clock,
  TrendingUp,
  TrendingDown,
  Minus,
  ShieldAlert,
  Database,
  Activity,
} from "lucide-react";
import IMHeader from "./IMHeader";
import IMStatusBadge from "./IMStatusBadge";
import IMBacktestView from "./IMBacktestView";
import { apiUrl } from "../../lib/backendUrl";

// ── Types (mirror of AutoHedgeSignal from backend types.ts) ─────────────────

type SignalStatus = "WAIT" | "READY" | "ENTERED" | "PROFIT" | "LOSS" | "EXITED" | "NO_TRADE" | "BLOCKED";
type StrategyType = "BULL_PUT_SPREAD" | "BEAR_CALL_SPREAD" | "IRON_CONDOR" | "NO_TRADE";
type RegimeType = "BULLISH" | "BEARISH" | "RANGE" | "HIGH_VOLATILITY" | "EVENT_RISK" | "UNCLEAR";

interface SignalLeg {
  symbol: string;
  strike: number;
  optionType: "CE" | "PE";
  ltp: number;
  bid: number;
  ask: number;
  iv: number;
  delta: number;
  gamma?: number;
}

interface ChargeBreakdown {
  brokerage: number;
  stt: number;
  exchangeFees: number;
  gst: number;
  sebiFees: number;
  stampDuty: number;
  estimatedSlippage: number;
  totalCharges: number;
  netPnl: number;
}

interface SignalData {
  symbol: string;
  timestamp: string;
  regime: RegimeType;
  score: number;
  action: StrategyType;
  expiry: string;
  spotPrice: number;
  sellLeg?: SignalLeg;
  buyLeg?: SignalLeg;
  netCredit: number;
  maxProfit: number;
  maxLoss: number;
  stopLossSpread: number;
  targetSpread: number;
  quantityLots: number;
  totalQuantity: number;
  marginRequired: number;
  charges: ChargeBreakdown;
  expectedNetPnl: number;
  riskPercentage: number;
  rewardRiskRatio: number;
  status: SignalStatus;
  reasons: string[];
  dataSource?: string;
  spotSource?: string;
  optionChainSource?: string;
  dataFreshnessMs?: number;
  decisionTimestamp?: string;
  signalId?: string;
}

interface ApiResponse {
  success: boolean;
  signal: SignalData;
  isRealData: boolean;
  dataHealth?: { isHealthy: boolean; isStale: boolean };
}

// ── UI state machine ─────────────────────────────────────────────────────────

type PageState =
  | { kind: "loading" }
  | { kind: "disconnected"; error: string }
  | { kind: "no_trade"; signal: SignalData; isReal: boolean }
  | { kind: "signal"; signal: SignalData; isReal: boolean };

// ── Helpers ─────────────────────────────────────────────────────────────────

function fmt(n: number, dec = 2): string {
  return n.toLocaleString("en-IN", { minimumFractionDigits: dec, maximumFractionDigits: dec });
}

function fmtAge(ms: number): string {
  if (!ms || ms < 0) return "—";
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  return `${(ms / 60000).toFixed(1)}m`;
}

function strategyLabel(action: StrategyType): string {
  if (action === "BULL_PUT_SPREAD") return "BULL PUT SPREAD";
  if (action === "BEAR_CALL_SPREAD") return "BEAR CALL SPREAD";
  if (action === "IRON_CONDOR") return "IRON CONDOR";
  return "NO TRADE";
}

function regimeIcon(regime: RegimeType) {
  if (regime === "BULLISH") return <TrendingUp className="w-4 h-4 text-emerald-400" />;
  if (regime === "BEARISH") return <TrendingDown className="w-4 h-4 text-rose-400" />;
  return <Minus className="w-4 h-4 text-amber-400" />;
}

function regimeColor(regime: RegimeType): string {
  if (regime === "BULLISH") return "text-emerald-400";
  if (regime === "BEARISH") return "text-rose-400";
  if (regime === "RANGE") return "text-amber-400";
  if (regime === "HIGH_VOLATILITY") return "text-orange-400";
  if (regime === "EVENT_RISK") return "text-violet-400";
  return "text-slate-400";
}

// ── Sub-components ───────────────────────────────────────────────────────────

function MetricTile({ label, value, accent }: { label: string; value: string; accent?: string }) {
  return (
    <div className="px-3 py-2 rounded-lg bg-slate-900/60 border border-slate-800/50 space-y-0.5">
      <div className="text-[9px] text-slate-600 font-mono uppercase tracking-wider">{label}</div>
      <div className={`text-xs font-bold font-mono ${accent ?? "text-slate-200"}`}>{value}</div>
    </div>
  );
}

function LegRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between text-[10px] font-mono py-1.5 border-b border-slate-800/40 last:border-0">
      <span className="text-slate-500">{label}</span>
      <span className="text-slate-200 font-semibold">{value}</span>
    </div>
  );
}

// ── Loading ──────────────────────────────────────────────────────────────────

function LoadingCard() {
  return (
    <div className="flex flex-col items-center justify-center py-20 gap-4 text-slate-500 font-mono text-xs">
      <RefreshCw className="w-8 h-8 animate-spin text-cyan-400" />
      <span>Fetching signal from backend…</span>
    </div>
  );
}

// ── Backend disconnected ─────────────────────────────────────────────────────

function DisconnectedCard({ error, onRetry }: { error: string; onRetry: () => void }) {
  return (
    <div className="p-6 rounded-2xl border border-rose-500/30 bg-rose-500/5 space-y-4">
      <div className="flex items-center gap-3">
        <WifiOff className="w-6 h-6 text-rose-400 shrink-0" />
        <div>
          <div className="text-sm font-bold text-rose-400 font-mono uppercase tracking-widest">
            BACKEND DISCONNECTED
          </div>
          <div className="text-[10px] text-slate-500 font-mono mt-0.5">{error}</div>
        </div>
      </div>
      <div className="text-[10px] text-slate-600 font-mono leading-relaxed">
        The frontend cannot reach the backend. Check that{" "}
        <span className="text-amber-400">NEXT_PUBLIC_BACKEND_URL</span> is correctly set in your
        Vercel environment variables and points to your deployed Render backend.
      </div>
      <button
        onClick={onRetry}
        className="flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-mono font-bold text-rose-300 border border-rose-500/30 bg-rose-500/10 hover:bg-rose-500/20 transition-colors"
      >
        <RefreshCw className="w-3.5 h-3.5" /> RETRY
      </button>
    </div>
  );
}

// ── NO TRADE card ────────────────────────────────────────────────────────────

function NoTradeCard({ signal, isReal }: { signal: SignalData; isReal: boolean }) {
  const isBlocked = signal.status === "BLOCKED";
  const freshness = signal.dataFreshnessMs !== undefined ? fmtAge(signal.dataFreshnessMs) : "—";

  return (
    <div className="p-6 rounded-2xl border border-amber-500/30 bg-amber-500/5 space-y-5">
      {/* Header */}
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          {isBlocked ? (
            <ShieldAlert className="w-6 h-6 text-rose-400 shrink-0" />
          ) : (
            <AlertTriangle className="w-6 h-6 text-amber-400 shrink-0" />
          )}
          <div>
            <div
              className={`text-sm font-bold font-mono uppercase tracking-widest ${
                isBlocked ? "text-rose-400" : "text-amber-400"
              }`}
            >
              {isBlocked ? "TRADE BLOCKED" : "NO TRADE"}
            </div>
            <div className="text-[10px] text-slate-500 font-mono">
              Strategy engine found no valid setup
            </div>
          </div>
        </div>
        <IMStatusBadge status={isReal ? "CONNECTED" : "WARNING"} size="xs" />
      </div>

      {/* Regime + Meta */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
        <MetricTile label="Regime" value={signal.regime} accent={regimeColor(signal.regime)} />
        <MetricTile label="Spot" value={signal.spotPrice > 0 ? `₹${fmt(signal.spotPrice, 0)}` : "N/A"} />
        <MetricTile label="Data Source" value={signal.dataSource ?? "UNKNOWN"} accent={isReal ? "text-emerald-400" : "text-amber-400"} />
        <MetricTile label="Data Age" value={freshness} />
      </div>

      {/* Rejection reasons */}
      <div className="space-y-2">
        <div className="text-[9px] text-slate-600 font-mono uppercase tracking-widest">
          Rejection Reasons ({signal.reasons.length})
        </div>
        <div className="space-y-1.5 max-h-48 overflow-y-auto pr-1">
          {signal.reasons.map((r, i) => {
            const isMaxLoss = r.includes("MAX_LOSS_EXCEEDS_1000_INR");
            const isData = r.includes("DATA_STALE") || r.includes("UNAVAILABLE") || r.includes("REAL_OPTION");
            return (
              <div
                key={i}
                className={`text-[10px] font-mono px-2.5 py-1.5 rounded-lg border ${
                  isMaxLoss
                    ? "border-rose-500/30 bg-rose-500/5 text-rose-300"
                    : isData
                    ? "border-amber-500/30 bg-amber-500/5 text-amber-300"
                    : "border-slate-700/40 bg-slate-900/40 text-slate-400"
                }`}
              >
                {r}
              </div>
            );
          })}
          {signal.reasons.length === 0 && (
            <div className="text-[10px] text-slate-600 font-mono">No reasons returned by backend.</div>
          )}
        </div>
      </div>

      {/* Genuine-data gate status */}
      <div className="flex flex-wrap gap-2">
        <div className={`inline-flex items-center gap-1.5 text-[9px] font-mono px-2 py-1 rounded border ${
          isReal
            ? "border-emerald-500/30 bg-emerald-500/5 text-emerald-400"
            : "border-amber-500/30 bg-amber-500/5 text-amber-400"
        }`}>
          <Database className="w-3 h-3" />
          {isReal ? "GENUINE DATA" : "NO REAL DATA — TRADE GATE BLOCKED"}
        </div>
        <div className="inline-flex items-center gap-1.5 text-[9px] font-mono px-2 py-1 rounded border border-slate-700/40 bg-slate-900/40 text-slate-400">
          <Clock className="w-3 h-3" />
          {signal.timestamp ? new Date(signal.timestamp).toLocaleTimeString("en-IN") : "—"}
        </div>
        {signal.signalId && (
          <div className="inline-flex items-center gap-1.5 text-[9px] font-mono px-2 py-1 rounded border border-slate-800/40 bg-slate-900/40 text-slate-600">
            ID: {signal.signalId}
          </div>
        )}
      </div>

      <div className="text-[9px] text-slate-600 font-mono">
        ⚠ PAPER MODE — ₹1,000 max-loss gate enforced by backend. This message is the authoritative signal.
      </div>
    </div>
  );
}

// ── Real Signal Card ─────────────────────────────────────────────────────────

function SignalCard({ signal, isReal }: { signal: SignalData; isReal: boolean }) {
  const stratLabel = strategyLabel(signal.action);
  const freshness = signal.dataFreshnessMs !== undefined ? fmtAge(signal.dataFreshnessMs) : "—";

  // Build legs display
  const legs: { label: string; value: string }[] = [];
  if (signal.sellLeg) {
    legs.push({
      label: `Sell ${signal.sellLeg.optionType === "PE" ? "Put" : "Call"}`,
      value: `${signal.sellLeg.strike} ${signal.sellLeg.optionType} @ ₹${fmt(signal.sellLeg.ltp)}`,
    });
  }
  if (signal.buyLeg) {
    legs.push({
      label: `Buy ${signal.buyLeg.optionType === "PE" ? "Put (Hedge)" : "Call (Hedge)"}`,
      value: `${signal.buyLeg.strike} ${signal.buyLeg.optionType} @ ₹${fmt(signal.buyLeg.ltp)}`,
    });
  }
  // Iron Condor has a second pair — sellLeg2 / buyLeg2 would appear in reasons if present
  // The backend includes both pairs' legs in the candidate spread

  return (
    <div className="p-5 rounded-2xl border border-emerald-500/30 bg-emerald-500/5 space-y-4">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span className="text-sm font-bold text-slate-100 font-mono">{stratLabel}</span>
            <span className="text-[9px] px-1.5 py-0.5 rounded bg-emerald-500/15 text-emerald-400 border border-emerald-500/30 font-mono font-bold">
              GENUINE SIGNAL
            </span>
          </div>
          <span className="text-[10px] text-slate-500 font-mono">Credit Spread · Defined Risk · Paper</span>
        </div>
        <div className="text-right">
          <div className="text-lg font-bold text-cyan-400 font-mono">
            {signal.score}<span className="text-xs text-slate-500">/100</span>
          </div>
          <div className="text-[10px] text-slate-500 font-mono">SETUP SCORE</div>
        </div>
      </div>

      {/* Regime */}
      <div className="flex items-center gap-2">
        {regimeIcon(signal.regime)}
        <span className={`text-xs font-mono font-bold ${regimeColor(signal.regime)}`}>
          {signal.regime}
        </span>
        <span className="text-[10px] text-slate-500 font-mono">· Expiry: {signal.expiry}</span>
      </div>

      {/* Legs */}
      {legs.length > 0 && (
        <div className="space-y-1">
          <div className="text-[9px] text-slate-600 font-mono uppercase tracking-widest">Legs</div>
          {legs.map((l) => <LegRow key={l.label} label={l.label} value={l.value} />)}
        </div>
      )}

      {/* Metrics grid */}
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
        <MetricTile label="Entry Credit" value={`₹${fmt(signal.netCredit)} / unit`} />
        <MetricTile label="Stop Loss" value={`₹${fmt(signal.stopLossSpread)} (1.5×)`} />
        <MetricTile label="Target" value={`₹${fmt(signal.targetSpread)} (50%)`} />
        <MetricTile
          label="Max Profit"
          value={`₹${fmt(signal.maxProfit)}`}
          accent="text-emerald-400"
        />
        <MetricTile
          label="Max Loss (incl. charges)"
          value={`₹${fmt(signal.maxLoss)}`}
          accent="text-rose-400"
        />
        <MetricTile
          label="Risk %"
          value={`${fmt(signal.riskPercentage)}%`}
          accent="text-amber-400"
        />
        <MetricTile label="Reward / Risk" value={`${fmt(signal.rewardRiskRatio)}×`} />
        <MetricTile label="Margin" value={`₹${fmt(signal.marginRequired, 0)}`} />
        <MetricTile
          label="Total Charges"
          value={`₹${fmt(signal.charges?.totalCharges ?? 0)}`}
        />
        <MetricTile
          label="Net P&L (best)"
          value={`+₹${fmt(signal.expectedNetPnl)}`}
          accent="text-emerald-400"
        />
        <MetricTile label="Lots" value={`${signal.quantityLots} (${signal.totalQuantity} qty)`} />
        <MetricTile label="Spot" value={`₹${fmt(signal.spotPrice, 0)}`} />
      </div>

      {/* Provenance */}
      <div className="flex flex-wrap gap-1.5">
        <div
          className={`inline-flex items-center gap-1.5 text-[9px] font-mono px-2 py-1 rounded border ${
            isReal
              ? "border-emerald-500/30 bg-emerald-500/5 text-emerald-400"
              : "border-amber-500/30 bg-amber-500/5 text-amber-400"
          }`}
        >
          <Database className="w-3 h-3" />
          {isReal ? `GENUINE: ${signal.dataSource ?? "NSE"}` : "SYNTHETIC DATA"}
        </div>
        <div className="inline-flex items-center gap-1.5 text-[9px] font-mono px-2 py-1 rounded border border-slate-700/40 bg-slate-900/40 text-slate-400">
          <Activity className="w-3 h-3" />
          Age: {freshness}
        </div>
        <div className="inline-flex items-center gap-1.5 text-[9px] font-mono px-2 py-1 rounded border border-slate-700/40 bg-slate-900/40 text-slate-400">
          <Clock className="w-3 h-3" />
          {signal.timestamp ? new Date(signal.timestamp).toLocaleTimeString("en-IN") : "—"}
        </div>
      </div>

      {/* Reasons (structural analysis) */}
      {signal.reasons.length > 0 && (
        <details className="group">
          <summary className="text-[9px] text-slate-600 font-mono uppercase tracking-widest cursor-pointer hover:text-slate-400 transition-colors">
            Signal Reasons ({signal.reasons.length}) ▸
          </summary>
          <div className="mt-2 space-y-1 max-h-36 overflow-y-auto">
            {signal.reasons.map((r, i) => (
              <div key={i} className="text-[9px] font-mono text-slate-500 pl-2 border-l border-slate-800">
                {r}
              </div>
            ))}
          </div>
        </details>
      )}

      <div className="text-[9px] text-slate-600 font-mono text-center">
        ⚠ PAPER MODE — ₹1,000 max-loss gate enforced by backend · Live trading LOCKED OFF
      </div>
    </div>
  );
}

// ── DATA UNAVAILABLE card ────────────────────────────────────────────────────

function DataUnavailableCard({ reason }: { reason: string }) {
  return (
    <div className="p-6 rounded-2xl border border-slate-700/40 bg-slate-900/30 space-y-4">
      <div className="flex items-center gap-3">
        <XCircle className="w-6 h-6 text-slate-500 shrink-0" />
        <div>
          <div className="text-sm font-bold text-slate-400 font-mono uppercase tracking-widest">
            DATA UNAVAILABLE
          </div>
          <div className="text-[10px] text-slate-600 font-mono mt-0.5">{reason}</div>
        </div>
      </div>
      <div className="text-[9px] text-slate-600 font-mono">
        Synthetic / paper fallback data will NEVER be shown as a valid strategy.
        Waiting for genuine NSE/Dhan data before evaluating any setup.
      </div>
    </div>
  );
}

// ── Main page ────────────────────────────────────────────────────────────────

const POLL_INTERVAL_MS = 15_000; // 15 s — same cadence as data-health

export default function IMStrategy() {
  const [activeSubTab, setActiveSubTab] = useState<"strategy" | "backtest">("strategy");
  const [pageState, setPageState] = useState<PageState>({ kind: "loading" });
  const [lastFetched, setLastFetched] = useState<Date | null>(null);

  const fetchSignal = useCallback(async () => {
    try {
      const res = await fetch(apiUrl("/api/indian/signal"), { cache: "no-store" });
      if (!res.ok) {
        throw new Error(`HTTP ${res.status}: ${res.statusText}`);
      }
      const data: ApiResponse = await res.json();
      const signal = data.signal;
      const isReal = data.isRealData ?? false;

      setLastFetched(new Date());

      // Case: no real data returned and signal is synthetic/stale → DATA UNAVAILABLE
      if (
        !isReal &&
        (signal.status === "NO_TRADE" || signal.action === "NO_TRADE") &&
        signal.reasons.some(
          (r) =>
            r.includes("DATA_STALE") ||
            r.includes("REAL_OPTION_CHAIN_UNAVAILABLE") ||
            r.includes("REAL_OPTION_PRICE_UNAVAILABLE") ||
            r.includes("REAL_GAMMA_UNAVAILABLE") ||
            r.includes("REAL_IV_UNAVAILABLE")
        )
      ) {
        setPageState({ kind: "no_trade", signal, isReal });
        return;
      }

      // Case: backend explicitly returned NO_TRADE for any reason
      if (signal.status === "NO_TRADE" || signal.status === "BLOCKED" || signal.action === "NO_TRADE") {
        setPageState({ kind: "no_trade", signal, isReal });
        return;
      }

      // Case: valid signal
      setPageState({ kind: "signal", signal, isReal });
    } catch (err: unknown) {
      const msg =
        err instanceof Error
          ? err.message
          : "Network error — backend may be unreachable";
      setPageState({ kind: "disconnected", error: msg });
    }
  }, []);

  useEffect(() => {
    if (activeSubTab !== "strategy") return;
    fetchSignal();
    const id = setInterval(fetchSignal, POLL_INTERVAL_MS);
    return () => clearInterval(id);
  }, [fetchSignal, activeSubTab]);

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div className="space-y-6">
      {/* Page title + sub-tab navigation */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <div>
            <h2 className="text-xl font-bold text-slate-100 tracking-tight">STRATEGY &amp; SIGNALS</h2>
            <p className="text-xs text-slate-400 font-mono">
              Live NIFTY hedge signal from HedgingStrategyEngine
            </p>
          </div>
          <IMStatusBadge status="PAPER MODE" size="sm" />
        </div>

        <div className="flex items-center gap-3">
          {lastFetched && activeSubTab === "strategy" && (
            <div className="flex items-center gap-1.5 text-[10px] font-mono text-slate-500">
              <Wifi className="w-3 h-3 text-cyan-500" />
              {lastFetched.toLocaleTimeString("en-IN")}
            </div>
          )}
          {activeSubTab === "strategy" && (
            <button
              onClick={fetchSignal}
              title="Refresh signal"
              className="p-1.5 rounded-lg border border-slate-700 text-slate-500 hover:text-cyan-400 hover:border-cyan-500/30 transition-colors"
            >
              <RefreshCw className="w-3.5 h-3.5" />
            </button>
          )}

          <div className="flex items-center p-1 rounded-xl bg-slate-900 border border-slate-800 font-mono text-xs">
            <button
              onClick={() => setActiveSubTab("strategy")}
              className={`px-3 py-1.5 rounded-lg transition-colors font-bold ${
                activeSubTab === "strategy"
                  ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/30"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              STRATEGY SETUPS
            </button>
            <button
              onClick={() => setActiveSubTab("backtest")}
              className={`px-3 py-1.5 rounded-lg transition-colors font-bold ${
                activeSubTab === "backtest"
                  ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/30"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              WALK-FORWARD BACKTEST
            </button>
          </div>
        </div>
      </div>

      {activeSubTab === "backtest" ? (
        <IMBacktestView />
      ) : (
        <>
          {/* Market data status bar */}
          <IMHeader />

          {/* Signal content */}
          {pageState.kind === "loading" && <LoadingCard />}

          {pageState.kind === "disconnected" && (
            <DisconnectedCard error={pageState.error} onRetry={fetchSignal} />
          )}

          {pageState.kind === "no_trade" && (
            <NoTradeCard signal={pageState.signal} isReal={pageState.isReal} />
          )}

          {pageState.kind === "signal" && (
            <>
              {/* Warn if signal data is synthetic */}
              {!pageState.isReal && (
                <DataUnavailableCard reason="Backend returned a signal but data source is not genuine (SYNTHETIC/STALE). Displaying NO TRADE guard." />
              )}
              {pageState.isReal && (
                <SignalCard signal={pageState.signal} isReal={pageState.isReal} />
              )}
              {/* If signal kind but isReal=false, also show NO_TRADE reasoning */}
              {!pageState.isReal && (
                <NoTradeCard
                  signal={{ ...pageState.signal, status: "NO_TRADE", reasons: ["GENUINE_DATA_REQUIRED: Signal data source is not real. No strategy setup will be shown until genuine NSE/Dhan data is confirmed.", ...pageState.signal.reasons] }}
                  isReal={false}
                />
              )}
            </>
          )}

          {/* Permanent safety footer */}
          <div className="text-[9px] text-slate-600 font-mono text-center space-y-0.5">
            <div>
              ⚠ PAPER MODE — Strategy evaluates defined-risk option spreads via
              HedgingStrategyEngine with ₹1,000 per-trade max-loss gate.
            </div>
            <div className="text-slate-700">
              PAPER_TRADING=true · LIVE_TRADING=false · BROKER_EXECUTION_ENABLED=false ·
              INDIAN_REAL_DATA_ONLY=true
            </div>
          </div>
        </>
      )}
    </div>
  );
}
