/**
 * PineSignalEngine
 * ================
 * Backend strategy signal-detection engine built on top of PineLiquidityEngine.
 *
 * Implements signal detection for five supported strategy categories:
 *   1. Liquidity Sweep
 *   2. Swing High / Swing Low
 *   3. EQH / EQL
 *   4. PWH / PWL
 *   5. Sweep + Engulfing
 *
 * NOTE ON ORDER BLOCK STRATEGY:
 *   Order Block Create + Retest + Entry is intentionally NOT IMPLEMENTED because
 *   the original Pine indicator does not define an Order Block algorithm.
 *   Infrastructure types exist for future expansion, but no ORDER_BLOCK strategy
 *   signals are generated by this engine.
 *
 * Design Constraints:
 *   - Analytical observer — DOES NOT modify PineLiquidityEngine calculations.
 *   - VERY IMPORTANT: DOES NOT auto-execute trades.
 *   - Stable deterministic deduplication (no random IDs).
 *   - Exposes active signals for user manual execution via frontend.
 */
import {
  Candle,
  ActiveLevel,
  PineSignal,
  PineStrategyCategory,
  OrderBlockState,
} from "./PineTypes";
import { PineLiquidityEngine } from "./PineLiquidityEngine";

export interface OrderBlockData {
  id: string;
  instrument: string;
  timeframe: string;
  direction: "BUY" | "SELL"; // BUY OB (bullish), SELL OB (bearish)
  top: number;
  bottom: number;
  state: OrderBlockState;
  createdAtTime: string;
  creationCandleTime?: string;
  retestedAtTime?: string;
}

export class PineSignalEngine {
  private activeSignals: Map<string, PineSignal> = new Map();
  private orderBlocks: Map<string, OrderBlockData> = new Map();
  private signalHistory: PineSignal[] = [];

  constructor() {}

  /**
   * Evaluates incoming candle & active Pine levels to detect strategy signals.
   * Returns any newly detected PineSignal events.
   */
  public evaluateCandle(
    instrument: string,
    candle: Candle,
    prevCandle: Candle | null,
    engine: PineLiquidityEngine
  ): PineSignal[] {
    const activeLevels = engine.getActiveLevels();
    const timeframe = `${engine.getChartTF() < 15 ? 15 : engine.getChartTF()}M`;
    const detected: PineSignal[] = [];

    // 1. Evaluate Liquidity Sweep, Swing, EQH/EQL, PWH/PWL Signals
    for (const level of activeLevels) {
      if (["PREMIUM", "DISCOUNT", "EQUILIBRIUM"].includes(level.type)) continue;

      // Check level interaction (high reached for resistance, low for support)
      const isUpsideTouch = candle.high >= level.price;
      const isDownsideTouch = candle.low <= level.price;

      // ─── A. General Liquidity Sweep ──────────────────────────────────────
      if (isUpsideTouch && (level.type === "EQH" || level.type === "PWH" || level.type === "SWH")) {
        const sig = this.createSignal({
          instrument,
          candle,
          timeframe: level.timeframe || timeframe,
          direction: "SELL",
          strategy: "LIQUIDITY_SWEEP",
          signalType: "SELL_SETUP",
          triggerPrice: candle.high,
          referenceLevel: level.label,
          referenceLevelType: level.type,
          notes: `Upside sweep of ${level.label} @ ${level.price.toFixed(2)}`,
        });
        if (sig) detected.push(sig);
      } else if (isDownsideTouch && (level.type === "EQL" || level.type === "PWL" || level.type === "SWL")) {
        const sig = this.createSignal({
          instrument,
          candle,
          timeframe: level.timeframe || timeframe,
          direction: "BUY",
          strategy: "LIQUIDITY_SWEEP",
          signalType: "BUY_SETUP",
          triggerPrice: candle.low,
          referenceLevel: level.label,
          referenceLevelType: level.type,
          notes: `Downside sweep of ${level.label} @ ${level.price.toFixed(2)}`,
        });
        if (sig) detected.push(sig);
      }

      // ─── B. Swing High / Swing Low Specific Strategy ─────────────────────
      if (level.type === "SWH" && isUpsideTouch) {
        const sig = this.createSignal({
          instrument,
          candle,
          timeframe: level.timeframe || timeframe,
          direction: "SELL",
          strategy: "SWING",
          signalType: "SELL_SETUP",
          triggerPrice: candle.high,
          referenceLevel: level.label,
          referenceLevelType: "SWH",
          notes: `Major Swing High liquidity interaction @ ${level.price.toFixed(2)}`,
        });
        if (sig) detected.push(sig);
      } else if (level.type === "SWL" && isDownsideTouch) {
        const sig = this.createSignal({
          instrument,
          candle,
          timeframe: level.timeframe || timeframe,
          direction: "BUY",
          strategy: "SWING",
          signalType: "BUY_SETUP",
          triggerPrice: candle.low,
          referenceLevel: level.label,
          referenceLevelType: "SWL",
          notes: `Major Swing Low liquidity interaction @ ${level.price.toFixed(2)}`,
        });
        if (sig) detected.push(sig);
      }

      // ─── C. EQH / EQL Specific Strategy ──────────────────────────────────
      if (level.type === "EQH" && isUpsideTouch) {
        const sig = this.createSignal({
          instrument,
          candle,
          timeframe: level.timeframe || timeframe,
          direction: "SELL",
          strategy: "EQH_EQL",
          signalType: "SELL_SETUP",
          triggerPrice: candle.high,
          referenceLevel: level.label,
          referenceLevelType: "EQH",
          notes: `HTF EQH liquidity interaction (${level.timeframe}) @ ${level.price.toFixed(2)}`,
        });
        if (sig) detected.push(sig);
      } else if (level.type === "EQL" && isDownsideTouch) {
        const sig = this.createSignal({
          instrument,
          candle,
          timeframe: level.timeframe || timeframe,
          direction: "BUY",
          strategy: "EQH_EQL",
          signalType: "BUY_SETUP",
          triggerPrice: candle.low,
          referenceLevel: level.label,
          referenceLevelType: "EQL",
          notes: `HTF EQL liquidity interaction (${level.timeframe}) @ ${level.price.toFixed(2)}`,
        });
        if (sig) detected.push(sig);
      }

      // ─── D. PWH / PWL Specific Strategy ──────────────────────────────────
      if (level.type === "PWH" && isUpsideTouch) {
        const sig = this.createSignal({
          instrument,
          candle,
          timeframe: "1W",
          direction: "SELL",
          strategy: "PWH_PWL",
          signalType: "SELL_SETUP",
          triggerPrice: candle.high,
          referenceLevel: level.label,
          referenceLevelType: "PWH",
          notes: `Previous Week High (PWH) interaction @ ${level.price.toFixed(2)}`,
        });
        if (sig) detected.push(sig);
      } else if (level.type === "PWL" && isDownsideTouch) {
        const sig = this.createSignal({
          instrument,
          candle,
          timeframe: "1W",
          direction: "BUY",
          strategy: "PWH_PWL",
          signalType: "BUY_SETUP",
          triggerPrice: candle.low,
          referenceLevel: level.label,
          referenceLevelType: "PWL",
          notes: `Previous Week Low (PWL) interaction @ ${level.price.toFixed(2)}`,
        });
        if (sig) detected.push(sig);
      }

      // ─── E. Sweep + Engulfing Strategy ───────────────────────────────────
      if (prevCandle) {
        // Bullish Sweep + Engulfing: Downside liquidity swept + bullish body engulfs prev body
        if (isDownsideTouch && (level.type === "EQL" || level.type === "PWL" || level.type === "SWL")) {
          const isBullishEngulf =
            candle.close > candle.open && // Bullish candle
            candle.open <= Math.max(prevCandle.open, prevCandle.close) &&
            candle.close >= Math.max(prevCandle.open, prevCandle.close) &&
            candle.open <= Math.min(prevCandle.open, prevCandle.close); // Body fully contains prev body

          if (isBullishEngulf) {
            const sig = this.createSignal({
              instrument,
              candle,
              timeframe: level.timeframe || timeframe,
              direction: "BUY",
              strategy: "SWEEP_ENGULFING",
              signalType: "BUY_SETUP",
              triggerPrice: candle.close,
              referenceLevel: level.label,
              referenceLevelType: level.type,
              notes: `Bullish Sweep + Engulfing pattern on ${level.label}`,
            });
            if (sig) detected.push(sig);
          }
        }

        // Bearish Sweep + Engulfing: Upside liquidity swept + bearish body engulfs prev body
        if (isUpsideTouch && (level.type === "EQH" || level.type === "PWH" || level.type === "SWH")) {
          const isBearishEngulf =
            candle.close < candle.open && // Bearish candle
            candle.open >= Math.max(prevCandle.open, prevCandle.close) &&
            candle.close <= Math.min(prevCandle.open, prevCandle.close); // Body fully contains prev body

          if (isBearishEngulf) {
            const sig = this.createSignal({
              instrument,
              candle,
              timeframe: level.timeframe || timeframe,
              direction: "SELL",
              strategy: "SWEEP_ENGULFING",
              signalType: "SELL_SETUP",
              triggerPrice: candle.close,
              referenceLevel: level.label,
              referenceLevelType: level.type,
              notes: `Bearish Sweep + Engulfing pattern on ${level.label}`,
            });
            if (sig) detected.push(sig);
          }
        }
      }
    }

    // ─── F. Order Block Strategy (NOT IMPLEMENTED) ───────────────────────────
    // Order Block Create + Retest + Entry is intentionally NOT IMPLEMENTED because
    // the original Pine indicator does not define an Order Block algorithm.
    // Infrastructure types exist, but no ORDER_BLOCK signal is generated.
    const obSignal = this.evaluateOrderBlocks(instrument, candle, prevCandle, timeframe);
    if (obSignal) detected.push(obSignal);

    return detected;
  }

  /**
   * Order Block Strategy: NOT IMPLEMENTED
   *
   * "Order Block Create + Retest + Entry is intentionally NOT IMPLEMENTED because the
   * original Pine indicator does not define an Order Block algorithm."
   *
   * Infrastructure types exist for future expansion, but this method explicitly
   * returns null so no ORDER_BLOCK strategy signals are generated.
   */
  private evaluateOrderBlocks(
    _instrument: string,
    _candle: Candle,
    _prevCandle: Candle | null,
    _timeframe: string
  ): PineSignal | null {
    return null;
  }

  /**
   * Helper to construct, deduplicate, and record PineSignal.
   * Uses stable deterministic IDs to prevent duplicate signals on repeated ticks.
   */
  private createSignal(params: {
    instrument: string;
    candle: Candle;
    timeframe: string;
    direction: "BUY" | "SELL";
    strategy: PineStrategyCategory;
    signalType: "BUY_SETUP" | "SELL_SETUP";
    triggerPrice: number;
    referenceLevel: string;
    referenceLevelType: "EQH" | "EQL" | "PWH" | "PWL" | "SWH" | "SWL" | "ORDER_BLOCK";
    orderBlockState?: OrderBlockState;
    notes?: string;
  }): PineSignal | null {
    const candleTime = params.candle.timestamp;
    const priceKey = Math.round(params.triggerPrice * 100);
    const signalId = `sig_${params.instrument}_${params.strategy}_${params.direction}_${params.referenceLevelType}_${priceKey}_${candleTime}`;

    // Deduplication check: Do not re-emit duplicate signal for same candle & reference
    if (this.activeSignals.has(signalId)) {
      return null;
    }

    const signal: PineSignal = {
      signalId,
      instrument: params.instrument,
      timestamp: new Date().toISOString(),
      timeframe: params.timeframe,
      direction: params.direction,
      strategy: params.strategy,
      signalType: params.signalType,
      triggerPrice: params.triggerPrice,
      referenceLevel: params.referenceLevel,
      referenceLevelType: params.referenceLevelType,
      confidence: 0.85,
      status: "ACTIVE",
      orderBlockState: params.orderBlockState,
      candleTimestamp: candleTime,
      notes: params.notes,
    };

    this.activeSignals.set(signalId, signal);
    this.signalHistory.push(signal);
    if (this.signalHistory.length > 500) this.signalHistory.shift();

    return signal;
  }

  public getActiveSignals(instrument?: string): PineSignal[] {
    const all = Array.from(this.activeSignals.values());
    if (!instrument) return all;
    return all.filter((s) => s.instrument === instrument);
  }

  public getSignalById(signalId: string): PineSignal | undefined {
    return this.activeSignals.get(signalId);
  }

  public getOrderBlocks(instrument?: string): OrderBlockData[] {
    const all = Array.from(this.orderBlocks.values());
    if (!instrument) return all;
    return all.filter((ob) => ob.instrument === instrument);
  }

  public clear(): void {
    this.activeSignals.clear();
    this.orderBlocks.clear();
    this.signalHistory = [];
  }
}
